# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: team_matchup.proto
# Protobuf Python Version: 6.32.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    32,
    0,
    '',
    'team_matchup.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12team_matchup.proto\"\xac\x01\n\x0bTeamMatchup\x12\x0c\n\x04team\x18\x01 \x01(\t\x12\x15\n\ropposing_team\x18\x02 \x01(\t\x12\x0f\n\x07is_home\x18\x03 \x01(\x08\x12\x1c\n\x14projected_team_total\x18\x04 \x01(\x02\x12%\n\x1dprojected_opposing_team_total\x18\x05 \x01(\x02\x12\x12\n\nover_under\x18\x06 \x01(\x02\x12\x0e\n\x06spread\x18\x07 \x01(\x02\".\n\x0cWeekMatchups\x12\x1e\n\x08matchups\x18\x01 \x03(\x0b\x32\x0c.TeamMatchupb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'team_matchup_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TEAMMATCHUP']._serialized_start=23
  _globals['_TEAMMATCHUP']._serialized_end=195
  _globals['_WEEKMATCHUPS']._serialized_start=197
  _globals['_WEEKMATCHUPS']._serialized_end=243
# @@protoc_insertion_point(module_scope)
