# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: optimizer_api.proto
# Protobuf Python Version: 6.32.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    32,
    0,
    '',
    'optimizer_api.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import player_pb2 as player__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13optimizer_api.proto\x1a\x0cplayer.proto\"c\n\x10OptimizerRequest\x12\x17\n\x0fplayer_id_locks\x18\x01 \x03(\t\x12\x12\n\nrandomness\x18\x02 \x01(\x02\x12\x13\n\x0bnum_lineups\x18\x03 \x01(\x05\x12\r\n\x05stack\x18\x04 \x01(\x08\"-\n\x11OptimizerResponse\x12\x18\n\x07lineups\x18\x01 \x03(\x0b\x32\x07.Lineup\"\x13\n\x11GetPlayersRequest\"/\n\x12GetPlayersResponse\x12\x19\n\x07players\x18\x01 \x01(\x0b\x32\x08.Playersb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'optimizer_api_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_OPTIMIZERREQUEST']._serialized_start=37
  _globals['_OPTIMIZERREQUEST']._serialized_end=136
  _globals['_OPTIMIZERRESPONSE']._serialized_start=138
  _globals['_OPTIMIZERRESPONSE']._serialized_end=183
  _globals['_GETPLAYERSREQUEST']._serialized_start=185
  _globals['_GETPLAYERSREQUEST']._serialized_end=204
  _globals['_GETPLAYERSRESPONSE']._serialized_start=206
  _globals['_GETPLAYERSRESPONSE']._serialized_end=253
# @@protoc_insertion_point(module_scope)
