# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: player.proto
# Protobuf Python Version: 6.32.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    32,
    0,
    '',
    'player.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cplayer.proto\"\x8d\x01\n\x06Player\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0c\n\x04team\x18\x03 \x01(\t\x12\x10\n\x08position\x18\x04 \x01(\t\x12\x0e\n\x06salary\x18\x05 \x01(\x05\x12\x0e\n\x06points\x18\x06 \x01(\x02\x12\x15\n\ropposing_team\x18\x07 \x01(\t\x12\x12\n\nsim_points\x18\x08 \x01(\x02\"#\n\x07Players\x12\x18\n\x07players\x18\x01 \x03(\x0b\x32\x07.Player\"\x89\x01\n\x06Lineup\x12;\n\x13position_to_players\x18\x01 \x03(\x0b\x32\x1e.Lineup.PositionToPlayersEntry\x1a\x42\n\x16PositionToPlayersEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x17\n\x05value\x18\x02 \x01(\x0b\x32\x08.Players:\x02\x38\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'player_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_LINEUP_POSITIONTOPLAYERSENTRY']._loaded_options = None
  _globals['_LINEUP_POSITIONTOPLAYERSENTRY']._serialized_options = b'8\001'
  _globals['_PLAYER']._serialized_start=17
  _globals['_PLAYER']._serialized_end=158
  _globals['_PLAYERS']._serialized_start=160
  _globals['_PLAYERS']._serialized_end=195
  _globals['_LINEUP']._serialized_start=198
  _globals['_LINEUP']._serialized_end=335
  _globals['_LINEUP_POSITIONTOPLAYERSENTRY']._serialized_start=269
  _globals['_LINEUP_POSITIONTOPLAYERSENTRY']._serialized_end=335
# @@protoc_insertion_point(module_scope)
